import React from 'react'
import Head from 'next/head'
import Dashboard from '../components/Dashboard.js'
function home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Dashboard />
        </div>
    )
}

export default home
